const Joi = require('joi')

module.exports = {
  createValidation: request => {
    const createSchema = {
    // Day: Joi.string().min(1).max(31).required(),
    // Month: Joi.string().required(),
    // Year: Joi.string().required(),
   Corporate_name: Joi.string().required(),
    // Corporate_governorate: Joi.string()
    //   .valid(
    //     "cairo",
    //     "Alex",
    //     "Ismalia",
    //     "aswan",
    //     "luxor",
    //     "Domiat",
    //     "Elbahr elahmar",
    //     "asiut",
    //     "Damnhor",
    //     "Bne sweif",
    //     "Bor saed",
    //     "Giza",
    //     "ganob sina",
    //     "suez",
    //     "faioum",
    //     "qena",
    //     "banha",
    //     "kafr elsheikh",
    //     "monofia",
    //     "aswan",
    //     "elmenia",
    //     "elwadi elgedid",
    //     "Qlioubia",
    //     "Gharbia",
    //     "aswan",
    //     "Sharaaia"
    //   )
    //   .required(),
    // Corporate_city: Joi.string().required()
    //   .valid(
    //     "Abnūb",
    //     "Abū al-Maṭāmīr",
    //     "Abū an-Numrus",
    //     "Abū Ḥammād",
    //     "Abū Ḥummuṣ",
    //     "Abū Kabīr",
    //     "Abū Qurqās",
    //     "Abū Ṣuwayr",
    //     "Abū Tīj",
    //     "Abū Tisht",
    //     "Aḍ-Ḍabah",
    //     "Ad-Dilinjāt",
    //     "Ajā",
    //     "Akhmīm",
    //     "Al-Arīsh",
    //     "Al-Ayyāṭ",
    //     "Al-Badārī",
    //     "Al-Badrashayn",
    //     "Al-Bājūr",
    //     "Al-Balyanā",
    //     "Al-Baṣaliyah Baḥri",
    //     "Al-Bāwīṭī",
    //     "Al-Bāyaḍiyah",
    //     "Al-Fashn",
    //     "Al-Fatḥ-An-Nāṣiriyah",
    //     "Al-Fayyūm",
    //     "Al-Ghanāyim ",
    //     "Al-Ghurdaqah",
    //     "Al-Ḥammām",
    //     "Al-Ḥāmūl",
    //     "Al-Ḥawāmidiyah",
    //     "Al-Ḥusayniyah",
    //     "Al-Ibrāhīmiyah",
    //     "Al-Idwah",
    //     "Al-Iskandariyah",
    //     "Al-Ismāīliyah",
    //     "Al-Jamāliyah",
    //     "Al-Jīzah ",
    //     "Al-Khānkah",
    //     "Al-Khārijah",
    //     "Al-Khuṣūṣ",
    //     "Al-Kurdy",
    //     "Al-Maḥallah al-Kubrā",
    //     "Al-Maḥmūdiyah",
    //     "Al-Manshāh",
    //     "Al-Manṣūrah",
    //     "Al-Manzilah",
    //     "Al-Marāghah",
    //     "Al-Maṭariyah",
    //     "Al-Minyā",
    //     "Al-Minyā al-Jadīdah",
    //     "Al-Qāhirah",
    //     "New Cairo",
    //     "Al-Qanāṭir al-Khayriyah",
    //     "Al-Qanāyāt",
    //     "Al-Qantarah",
    //     "Al-Qanṭarah Sharq",
    //     "Al-Qarnuh al-Jadīdah",
    //     "Al-Qaṣāṣīn al-Jadīdah",
    //     "Al-Qurayn",
    //     "Al-Quṣayr",
    //     "Al-Qūṣiyah",
    //     "Al-Ubūr",
    //     "Luxor",
    //     "Al-Waqf ",
    //     "Al-Wāsiṭā",
    //     "El Negaila",
    //     "An-New Nubariya",
    //     "Armant",
    //     "Ar-Radīsiyah Qiblī",
    //     "Ar-Rahmaniya",
    //     "Ar-Rawḍah",
    //     "Ar-Riyāḍ",
    //     "Ashmoun",
    //     "Ash-Shalātīn",
    //     "Sheikh Zayed City",
    //     "Sheikh Zuweid",
    //     "Ash-Shuhadā",
    //     "Ash-Shurūq",
    //     "Aṣ-Ṣaff",
    //     "New Salhia",
    //     "As-Sallūm",
    //     "As-Sanṭah",
    //     "As-Sarw",
    //     "As-Sibāiyah Gharb",
    //     "El Senbellawein",
    //     "Suez",
    //     "Aswān",
    //     "Asyut",
    //     "Aṭfīḥ",
    //     "At-Tall al-Kabīr",
    //     "Aṭ-Ṭūd",
    //     "El Tor",
    //     "Awlād Ṣaqr",
    //     "Awsīm",
    //     "Zagazig",
    //     "Az-Zarqā",
    //     "Az-Zayniyah Qiblī",
    //     "Badr",
    //     "Balṭīm",
    //     "Banhā",
    //     "Beni Mazar",
    //     "Beni Suef",
    //     "New Beni Suef",
    //     "Banī Ubayd",
    //     "Basyoun",
    //     "Bibā",
    //     "Bilbays",
    //     "Belqas",
    //     "Bīr al-Abd",
    //     "Birket el-Sab",
    //     "Biyalā",
    //     "Burj al-Arab",
    //     "Burj al-Barlus",
    //     "Port Said",
    //     "Damanhour",
    //     "Dar as-Salām",
    //     "Daraw",
    //     "Dayr Mawās",
    //     "Dairut",
    //     "Dikirnis",
    //     "Dishnā",
    //     "Desouk",
    //     "Diyarb Najm",
    //     "Dumyāṭ ",
    //     "Fayid ",
    //     "Faqous",
    //     "Fāraskūr  ",
    //     "Farshūṭ ",
    //     "Fuwah ",
    //     "Ḥawsh-Īsā",
    //     "Hihyā",
    //     "Ibsheway",
    //     "Edfu",
    //     "Idkū",
    //     "Ihnāsiyā",
    //     "Isnā",
    //     "Iṭsā",
    //     "Ityāy al-Bārūd",
    //     "Izbat al-Burj",
    //     "Girga",
    //     "Juhaynah",
    //     "Kafr ad-Dawwār",
    //     "Kafr al-Baṭṭīkh",
    //     "Kafr el-Sheikh",
    //     "Kafr az-Zayyāt",
    //     "Kafr Saad",
    //     "Kafr Ṣaqr",
    //     "Kafr Shukr",
    //     "Kawm Ḥamādah",
    //     "Kawm Umbū",
    //     "Kirdāsah",
    //     "10th of Ramadan City",
    //     "Madīnat as-Sādāt",
    //     "Madīnat Badr",
    //     "Madīnat Burj al-Arab al-Jadīdah",
    //     "Madīnat Dumyāṭ al-Jadīdah",
    //     "Madīnat Sittah Uktūbar",
    //     "Maghāghah ",
    //     "Maḥallah Damanah",
    //     "Mallawī ",
    //     "Manfalūṭ    ",
    //     "Manshat al-Qanāṭir",
    //     "Marsā Maṭrūḥ ",
    //     "Mashtūl as-Sūq ",
    //     "Maṭāy",
    //     "Minūf   ",
    //     "Minyā al-Qamḥ   ",
    //     "Minyat an-Naṣr  ",
    //     "Mīt Abū Ghālb ",
    //     "Mīt Ghamr   ",
    //     "Mīt Salsīl",
    //     "Munshāh Abū-Umar ",
    //     "Dakhla",
    //     "Muṭūbis",
    //     "Nabarūh ",
    //     "Naj-Ḥammādī",
    //     "Naqādah ",
    //     "Nāṣir Būsh",
    //     "Qahā   ",
    //     "Qallīn ",
    //     "Qalyūb",
    //     "Qifṭ",
    //     "Qinā",
    //     "Qūṣ",
    //     "Quṭūr",
    //     "Quwaysinā",
    //     "Rafaḥ",
    //     "Rās al-Bar",
    //     "Ras Ghārib ",
    //     "Rashīd",
    //     "Safājā",
    //     "Sāḥīl Salim",
    //     "Samālūṭ",
    //     "Samannūd",
    //     "Ṣān al-Ḥajar",
    //     "Sāqultah",
    //     "Sawhāj",
    //     "Sharm ash-Shaykh",
    //     "Shibīn al-Kawm",
    //     "Shibīn al-Qanāṭir",
    //     "Shirbīn",
    //     "Shubrā al-Khaymah",
    //     "Shubrākhīt",
    //     "Ṣidfā",
    //     "Sīdī Barrānī",
    //     "Sīdī Ghāzī",
    //     "Sīdī Sālim",
    //     "Sinnūris",
    //     "Sirs al-Layyānah",
    //     "Sīwa",
    //     "Sumusṭā al-Waqf",
    //     "Ṭahṭā",
    //     "Talā",
    //     "Ṭalkhā",
    //     "Tama al-Āmdīd",
    //     "Ṭāmiyah",
    //     "Ṭanṭā",
    //     "Ṭimā",
    //     "Ṭūkh",
    //     "Natron Valley",
    //     "Yūsuf aṣ-Ṣiddīq",
    //     "Ziftā"
    //   )
    //   .required()
      //,
    // Corporate_address: Joi.string().required(),
    // Investor_name: Joi.string().min(3).required(),
    // Investor_address: Joi.string().min(3).required(),
    // Investor_ID: Joi.string().required(),
    // Investor_DOB: Joi.string().required(),
    // Investor_nationality: Joi.string().valid(
    //     "Afghan",
    //     "Albanian",
    //     "Algerian",
    //     "Argentinian",
    //     "Australian",
    //     "Austrian",
    //     "Bangladeshi",
    //     "Belgian",
    //     "Bolivian",
    //     "Batswana",
    //     "Brazilian",
    //     "Bulgarian",
    //     "Cambodian",
    //     "Cameroonian",
    //     "Canadian",
    //     "Chilean",
    //     "Chinese",
    //     "Colombian",
    //     "Costa Rican",
    //     "Croatian",
    //     "Cuban",
    //     "Czech",
    //     "Danish",
    //     "Dominican",
    //     "Ecuadorian",
    //     "Egyptian",
    //     "Salvadorian",
    //     "English",
    //     "Estonian",
    //     "Ethiopian",
    //     "Fijian",
    //     "Finnish",
    //     "French",
    //     "German",
    //     "Ghanaian",
    //     "Greek",
    //     "Guatemalan",
    //     "Haitian",
    //     "Honduran",
    //     "Hungarian",
    //     "Icelandic",
    //     "Indian",
    //     "Indonesian",
    //     "Iranian",
    //     "Iraqi",
    //     "Irish",
    //     "Israeli",
    //     "Italian",
    //     "Jamaican",
    //     "Japanese",
    //     "Jordanian",
    //     "Kenyan",
    //     "Kuwaiti",
    //     "Lao",
    //     "Latvian",
    //     "Lebanese",
    //     "Libyan",
    //     "Lithuanian",
    //     "Malaysian",
    //     "Malian",
    //     "Maltese",
    //     "Mexican",
    //     "Mongolian",
    //     "Moroccan",
    //     "Mozambican",
    //     "Namibian",
    //     "Nepalese",
    //     "Dutch",
    //     "New Zealand",
    //     "Nicaraguan",
    //     "Nigerian",
    //     "Norwegian",
    //     "Pakistani",
    //     "Panamanian",
    //     "Paraguayan",
    //     "Peruvian",
    //     "Philippine",
    //     "Polish",
    //     "Portuguese",
    //     "Romanian",
    //     "Russian",
    //     "Saudi",
    //     "Scottish",
    //     "Senegalese",
    //     "Serbian",
    //     "Singaporean",
    //     "Slovak",
    //     "South African",
    //     "Korean",
    //     "Spanish",
    //     "Sri Lankan",
    //     "Sudanese",
    //     "Swedish",
    //     "Swiss",
    //     "Syrian",
    //     "Taiwanese",
    //     "Tajikistani",
    //     "Thai",
    //     "Tongan",
    //     "Tunisian",
    //     "Turkish",
    //     "Ukrainian",
    //     "Emirati",
    //     "British",
    //     "American",
    //     "Uruguayan",
    //     "Venezuelan",
    //     "Vietnamese",
    //     "Welsh",
    //     "Zambian",
    //     "Zimbabwean"
    //   ).required(),
    // Initial_capital: Joi.number()
    //   .integer()
    //   .min(50000)
    //   .max(999999999999)
    //   .required(),

     }

    return Joi.validate(request, createSchema)
}, 

    updateValidation: request => {
    const updateSchema = {
    // Day: Joi.string().min(1).max(31),
    // Month: Joi.string(),
    // Year: Joi.string(),
 
    Corporate_name: Joi.string(),
    // Corporate_governorate: Joi.string()
    //   .valid(
    //     "cairo",
    //     "Alex",
    //     "Ismalia",
    //     "aswan",
    //     "luxor",
    //     "Domiat",
    //     "Elbahr elahmar",
    //     "asiut",
    //     "Damnhor",
    //     "Bne sweif",
    //     "Bor saed",
    //     "Giza",
    //     "ganob sina",
    //     "suez",
    //     "faioum",
    //     "qena",
    //     "banha",
    //     "kafr elsheikh",
    //     "monofia",
    //     "aswan",
    //     "elmenia",
    //     "elwadi elgedid",
    //     "Qlioubia",
    //     "Gharbia",
    //     "aswan",
    //     "Sharaaia"
    //   )
    //   ,
    // Corporate_city: Joi.string()
    //   .valid(
    //     "Abnūb",
    //     "Abū al-Maṭāmīr",
    //     "Abū an-Numrus",
    //     "Abū Ḥammād",
    //     "Abū Ḥummuṣ",
    //     "Abū Kabīr",
    //     "Abū Qurqās",
    //     "Abū Ṣuwayr",
    //     "Abū Tīj",
    //     "Abū Tisht",
    //     "Aḍ-Ḍabah",
    //     "Ad-Dilinjāt",
    //     "Ajā",
    //     "Akhmīm",
    //     "Al-Arīsh",
    //     "Al-Ayyāṭ",
    //     "Al-Badārī",
    //     "Al-Badrashayn",
    //     "Al-Bājūr",
    //     "Al-Balyanā",
    //     "Al-Baṣaliyah Baḥri",
    //     "Al-Bāwīṭī",
    //     "Al-Bāyaḍiyah",
    //     "Al-Fashn",
    //     "Al-Fatḥ-An-Nāṣiriyah",
    //     "Al-Fayyūm",
    //     "Al-Ghanāyim ",
    //     "Al-Ghurdaqah",
    //     "Al-Ḥammām",
    //     "Al-Ḥāmūl",
    //     "Al-Ḥawāmidiyah",
    //     "Al-Ḥusayniyah",
    //     "Al-Ibrāhīmiyah",
    //     "Al-Idwah",
    //     "Al-Iskandariyah",
    //     "Al-Ismāīliyah",
    //     "Al-Jamāliyah",
    //     "Al-Jīzah ",
    //     "Al-Khānkah",
    //     "Al-Khārijah",
    //     "Al-Khuṣūṣ",
    //     "Al-Kurdy",
    //     "Al-Maḥallah al-Kubrā",
    //     "Al-Maḥmūdiyah",
    //     "Al-Manshāh",
    //     "Al-Manṣūrah",
    //     "Al-Manzilah",
    //     "Al-Marāghah",
    //     "Al-Maṭariyah",
    //     "Al-Minyā",
    //     "Al-Minyā al-Jadīdah",
    //     "Al-Qāhirah",
    //     "New Cairo",
    //     "Al-Qanāṭir al-Khayriyah",
    //     "Al-Qanāyāt",
    //     "Al-Qantarah",
    //     "Al-Qanṭarah Sharq",
    //     "Al-Qarnuh al-Jadīdah",
    //     "Al-Qaṣāṣīn al-Jadīdah",
    //     "Al-Qurayn",
    //     "Al-Quṣayr",
    //     "Al-Qūṣiyah",
    //     "Al-Ubūr",
    //     "Luxor",
    //     "Al-Waqf ",
    //     "Al-Wāsiṭā",
    //     "El Negaila",
    //     "An-New Nubariya",
    //     "Armant",
    //     "Ar-Radīsiyah Qiblī",
    //     "Ar-Rahmaniya",
    //     "Ar-Rawḍah",
    //     "Ar-Riyāḍ",
    //     "Ashmoun",
    //     "Ash-Shalātīn",
    //     "Sheikh Zayed City",
    //     "Sheikh Zuweid",
    //     "Ash-Shuhadā",
    //     "Ash-Shurūq",
    //     "Aṣ-Ṣaff",
    //     "New Salhia",
    //     "As-Sallūm",
    //     "As-Sanṭah",
    //     "As-Sarw",
    //     "As-Sibāiyah Gharb",
    //     "El Senbellawein",
    //     "Suez",
    //     "Aswān",
    //     "Asyut",
    //     "Aṭfīḥ",
    //     "At-Tall al-Kabīr",
    //     "Aṭ-Ṭūd",
    //     "El Tor",
    //     "Awlād Ṣaqr",
    //     "Awsīm",
    //     "Zagazig",
    //     "Az-Zarqā",
    //     "Az-Zayniyah Qiblī",
    //     "Badr",
    //     "Balṭīm",
    //     "Banhā",
    //     "Beni Mazar",
    //     "Beni Suef",
    //     "New Beni Suef",
    //     "Banī Ubayd",
    //     "Basyoun",
    //     "Bibā",
    //     "Bilbays",
    //     "Belqas",
    //     "Bīr al-Abd",
    //     "Birket el-Sab",
    //     "Biyalā",
    //     "Burj al-Arab",
    //     "Burj al-Barlus",
    //     "Port Said",
    //     "Damanhour",
    //     "Dar as-Salām",
    //     "Daraw",
    //     "Dayr Mawās",
    //     "Dairut",
    //     "Dikirnis",
    //     "Dishnā",
    //     "Desouk",
    //     "Diyarb Najm",
    //     "Dumyāṭ ",
    //     "Fayid ",
    //     "Faqous",
    //     "Fāraskūr  ",
    //     "Farshūṭ ",
    //     "Fuwah ",
    //     "Ḥawsh-Īsā",
    //     "Hihyā",
    //     "Ibsheway",
    //     "Edfu",
    //     "Idkū",
    //     "Ihnāsiyā",
    //     "Isnā",
    //     "Iṭsā",
    //     "Ityāy al-Bārūd",
    //     "Izbat al-Burj",
    //     "Girga",
    //     "Juhaynah",
    //     "Kafr ad-Dawwār",
    //     "Kafr al-Baṭṭīkh",
    //     "Kafr el-Sheikh",
    //     "Kafr az-Zayyāt",
    //     "Kafr Saad",
    //     "Kafr Ṣaqr",
    //     "Kafr Shukr",
    //     "Kawm Ḥamādah",
    //     "Kawm Umbū",
    //     "Kirdāsah",
    //     "10th of Ramadan City",
    //     "Madīnat as-Sādāt",
    //     "Madīnat Badr",
    //     "Madīnat Burj al-Arab al-Jadīdah",
    //     "Madīnat Dumyāṭ al-Jadīdah",
    //     "Madīnat Sittah Uktūbar",
    //     "Maghāghah ",
    //     "Maḥallah Damanah",
    //     "Mallawī ",
    //     "Manfalūṭ    ",
    //     "Manshat al-Qanāṭir",
    //     "Marsā Maṭrūḥ ",
    //     "Mashtūl as-Sūq ",
    //     "Maṭāy",
    //     "Minūf   ",
    //     "Minyā al-Qamḥ   ",
    //     "Minyat an-Naṣr  ",
    //     "Mīt Abū Ghālb ",
    //     "Mīt Ghamr   ",
    //     "Mīt Salsīl",
    //     "Munshāh Abū-Umar ",
    //     "Dakhla",
    //     "Muṭūbis",
    //     "Nabarūh ",
    //     "Naj-Ḥammādī",
    //     "Naqādah ",
    //     "Nāṣir Būsh",
    //     "Qahā   ",
    //     "Qallīn ",
    //     "Qalyūb",
    //     "Qifṭ",
    //     "Qinā",
    //     "Qūṣ",
    //     "Quṭūr",
    //     "Quwaysinā",
    //     "Rafaḥ",
    //     "Rās al-Bar",
    //     "Ras Ghārib ",
    //     "Rashīd",
    //     "Safājā",
    //     "Sāḥīl Salim",
    //     "Samālūṭ",
    //     "Samannūd",
    //     "Ṣān al-Ḥajar",
    //     "Sāqultah",
    //     "Sawhāj",
    //     "Sharm ash-Shaykh",
    //     "Shibīn al-Kawm",
    //     "Shibīn al-Qanāṭir",
    //     "Shirbīn",
    //     "Shubrā al-Khaymah",
    //     "Shubrākhīt",
    //     "Ṣidfā",
    //     "Sīdī Barrānī",
    //     "Sīdī Ghāzī",
    //     "Sīdī Sālim",
    //     "Sinnūris",
    //     "Sirs al-Layyānah",
    //     "Sīwa",
    //     "Sumusṭā al-Waqf",
    //     "Ṭahṭā",
    //     "Talā",
    //     "Ṭalkhā",
    //     "Tama al-Āmdīd",
    //     "Ṭāmiyah",
    //     "Ṭanṭā",
    //     "Ṭimā",
    //     "Ṭūkh",
    //     "Natron Valley",
    //     "Yūsuf aṣ-Ṣiddīq",
    //     "Ziftā"
    //   )
    //   ,
    // Corporate_address: Joi.string(),
    // Investor_name: Joi.string().min(3),
    // Investor_address: Joi.string().min(3),
    // Investor_ID: Joi.string(),
    // Investor_DOB: Joi.string(),
    // Investor_nationality: Joi.string().valid(
    //     "Afghan",
    //     "Albanian",
    //     "Algerian",
    //     "Argentinian",
    //     "Australian",
    //     "Austrian",
    //     "Bangladeshi",
    //     "Belgian",
    //     "Bolivian",
    //     "Batswana",
    //     "Brazilian",
    //     "Bulgarian",
    //     "Cambodian",
    //     "Cameroonian",
    //     "Canadian",
    //     "Chilean",
    //     "Chinese",
    //     "Colombian",
    //     "Costa Rican",
    //     "Croatian",
    //     "Cuban",
    //     "Czech",
    //     "Danish",
    //     "Dominican",
    //     "Ecuadorian",
    //     "Egyptian",
    //     "Salvadorian",
    //     "English",
    //     "Estonian",
    //     "Ethiopian",
    //     "Fijian",
    //     "Finnish",
    //     "French",
    //     "German",
    //     "Ghanaian",
    //     "Greek",
    //     "Guatemalan",
    //     "Haitian",
    //     "Honduran",
    //     "Hungarian",
    //     "Icelandic",
    //     "Indian",
    //     "Indonesian",
    //     "Iranian",
    //     "Iraqi",
    //     "Irish",
    //     "Israeli",
    //     "Italian",
    //     "Jamaican",
    //     "Japanese",
    //     "Jordanian",
    //     "Kenyan",
    //     "Kuwaiti",
    //     "Lao",
    //     "Latvian",
    //     "Lebanese",
    //     "Libyan",
    //     "Lithuanian",
    //     "Malaysian",
    //     "Malian",
    //     "Maltese",
    //     "Mexican",
    //     "Mongolian",
    //     "Moroccan",
    //     "Mozambican",
    //     "Namibian",
    //     "Nepalese",
    //     "Dutch",
    //     "New Zealand",
    //     "Nicaraguan",
    //     "Nigerian",
    //     "Norwegian",
    //     "Pakistani",
    //     "Panamanian",
    //     "Paraguayan",
    //     "Peruvian",
    //     "Philippine",
    //     "Polish",
    //     "Portuguese",
    //     "Romanian",
    //     "Russian",
    //     "Saudi",
    //     "Scottish",
    //     "Senegalese",
    //     "Serbian",
    //     "Singaporean",
    //     "Slovak",
    //     "South African",
    //     "Korean",
    //     "Spanish",
    //     "Sri Lankan",
    //     "Sudanese",
    //     "Swedish",
    //     "Swiss",
    //     "Syrian",
    //     "Taiwanese",
    //     "Tajikistani",
    //     "Thai",
    //     "Tongan",
    //     "Tunisian",
    //     "Turkish",
    //     "Ukrainian",
    //     "Emirati",
    //     "British",
    //     "American",
    //     "Uruguayan",
    //     "Venezuelan",
    //     "Vietnamese",
    //     "Welsh",
    //     "Zambian",
    //     "Zimbabwean"
    //   ),
    // Initial_capital: Joi.number()
    //   .integer()
    //   .min(50000)
    //   .max(999999999999),
     }
        return Joi.validate(request, updateSchema)
    }, 
}